//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Word {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Delete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Delete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Word.Delete", typeof(Delete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete With Equivalents.
        /// </summary>
        public static string DeleteWithEquivalents {
            get {
                return ResourceManager.GetString("DeleteWithEquivalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete But Keep Equivalents.
        /// </summary>
        public static string DeleteWithoutEquivalents {
            get {
                return ResourceManager.GetString("DeleteWithoutEquivalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Word.
        /// </summary>
        public static string DeleteWord {
            get {
                return ResourceManager.GetString("DeleteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to also discard the equivalents?.
        /// </summary>
        public static string DiscardEquivalents {
            get {
                return ResourceManager.GetString("DiscardEquivalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Equivalents.
        /// </summary>
        public static string KeepEquivalents {
            get {
                return ResourceManager.GetString("KeepEquivalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to keep the equivalents?.
        /// </summary>
        public static string WantToKeepEquivalents {
            get {
                return ResourceManager.GetString("WantToKeepEquivalents", resourceCulture);
            }
        }
    }
}
